# Generated by Django 6.0.3 on 2026-03-27 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Business description fed to the AI agent.')),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ai_error', models.TextField(blank=True, default='')),
                ('has_products', models.BooleanField(default=False)),
                ('has_inventory', models.BooleanField(default=False)),
                ('has_sales', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(help_text='The admin who created and owns this project.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(blank=True, help_text='Manager user auto-created when project is provisioned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_project', to=settings.AUTH_USER_MODEL)),
                ('staff', models.OneToOneField(blank=True, help_text='Staff user auto-created when project is provisioned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffed_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
