# Generated by Django 6.0.3 on 2026-03-28 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('sku', models.CharField(blank=True, default='', help_text='Stock Keeping Unit. Optional. Must be unique within project.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Selling price.', max_digits=10)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase / cost price. Optional.', max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, default='piece', help_text='Unit of measurement, e.g. piece, kg, litre.', max_length=50)),
                ('category', models.CharField(blank=True, default='', help_text='Free-text category label.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products are hidden from normal listings.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='projects.project')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sku__gt', '')), fields=('project', 'sku'), name='unique_sku_per_project')],
            },
        ),
    ]
