"""
ai_agent/models.py
───────────────────
Chat session models for the Business Analyst AI agent.

Design:
  AgentChat
    - One conversation session per (project, user) combination.
    - A user can open multiple separate chats in the same project.
    - title is auto-set from the first message content (truncated).
    - CASCADE-deleted when its project is deleted.

  AgentMessage
    - A single turn in a chat (role: user | assistant).
    - Ordered by created_at so history can be reconstructed in order.
    - Content is plain text; the agent SDK handles formatting.
    - CASCADE-deleted when its AgentChat is deleted.
"""

from django.db import models
from django.conf import settings


# ── AgentChat ─────────────────────────────────────────────────────────────────

class AgentChat(models.Model):
    """
    A stateful conversation session between a user and the Business Analyst
    agent, scoped to a specific project.
    """
    project = models.ForeignKey(
        "projects.Project",
        on_delete    = models.CASCADE,
        related_name = "agent_chats",
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete    = models.SET_NULL,
        null         = True,
        blank        = True,
        related_name = "agent_chats",
    )
    title = models.CharField(
        max_length = 200,
        default    = "New Chat",
        help_text  = "Auto-generated from the first message (first 80 chars).",
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering        = ["-updated_at"]
        verbose_name    = "Agent Chat"
        verbose_name_plural = "Agent Chats"

    def __str__(self) -> str:
        user_email = self.user.email if self.user else "deleted user"
        return f"Chat '{self.title}' — {user_email} [{self.project.name}]"


# ── AgentMessage ──────────────────────────────────────────────────────────────

class AgentMessage(models.Model):
    """
    A single message turn in an AgentChat.
    role=user    → sent by the human
    role=assistant → generated by the AI
    """

    class Role(models.TextChoices):
        USER      = "user",      "User"
        ASSISTANT = "assistant", "Assistant"

    chat = models.ForeignKey(
        AgentChat,
        on_delete    = models.CASCADE,
        related_name = "messages",
    )
    role    = models.CharField(max_length=20, choices=Role.choices)
    content = models.TextField()

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering        = ["created_at"]
        verbose_name    = "Agent Message"
        verbose_name_plural = "Agent Messages"

    def __str__(self) -> str:
        snippet = self.content[:60].replace("\n", " ")
        return f"[{self.role}] {snippet}…"
